"""
 Re-implementation of MUS-enumeration using MARCO.
"""

import time

import cpmpy as cp
from cpmpy.transformations.get_variables import get_variables

from .utils import make_assump_model



def marco(soft, hard=[], solver="ortools", map_solver="ortools", return_mus=True, return_mcs=True, do_solution_hint=True, enum_timing=None, log_events=None, name_of=None):
    """
        Enumerating minimal unsatisfiable subsets (MUSes) and minimal correction sets (MCSes)
        of unsatisfiable constraints.
        
        Iteratively generates a subset of constraints (the seed) and checks whether it is SAT.
        When the seed is SAT, it is grown to an MSS to derive an MCS.
        This MCS is then added to the Map solver as a set to hit
        In case the seed is UNSAT, the seed is shrunk to a real MUS and returned.
        The Map-solver is instructed to not generated any superset of this MUS as next seeds

        Based on:
            Liffiton, Mark H., et al. "Fast, flexible MUS enumeration." Constraints 21 (2016): 223-250.
    
        :param: solver: name of a solver, must support assumptions (e.g, "ortools", "exact", "z3" or "pysat")
        :param: map_solver: the hitting-set (MAP) solver to use, ideally incremental such as "gurobi", "pysat" or "exact"
        :param: return_mus: whether the algorithm should return MUSes
        :param: return_mcs: whether the algorithm should return MCSes
        :param: do_solution_hint: when true, will favor large seeds generated by the map-solver, and hence more likely
                                     to return MUSes. Especially useful when `return_mus=True`.
        :param: enum_timing: optional list; if given, the wall-clock time of the full enumeration loop
                             (from the first map-solver call until the map solver returns UNSAT) is appended to it
        :param: log_events: optional list; if given, one record is appended per map-solver iteration:
                            ``{"type": "iter", "seed": [names], "kind": "MUS"/"MCS", "result": [names]}``,
                            where the seed is the subset the map solver returned and the result is the
                            MUS/MCS derived from it (chronological order)
        :param: name_of: optional dict ``id(constraint) -> human-readable name``, used to render the
                         ``log_events`` seed/result; falls back to a short object id if missing

    """

    assert hasattr(cp.SolverLookup.get(solver), "get_core"), "MARCO requires a solver that supports assumption variables"

    model, soft, assump = make_assump_model(soft, hard)
    dmap = dict(zip(assump, soft))
    s = cp.SolverLookup.get(solver, model)

    # map solver for computing hitting sets
    map_solver = cp.SolverLookup.get(map_solver)
    do_solution_hint = do_solution_hint and hasattr(map_solver, 'solution_hint')  # solver may not support solution hinting...

    map_solver += cp.any(assump)
    if do_solution_hint:
        hint = [1]*len(assump)
        map_solver.solution_hint(assump, hint) # we want large subsets, more likely to be a MUS

    deletion_order = {a : -len(get_variables(dmap[a])) for a in assump} # avoid recomputing

    def _nm(constraint):
        return name_of.get(id(constraint), f"c@{id(constraint)}") if name_of else f"c@{id(constraint)}"

    _t_enum_start = time.perf_counter()
    while map_solver.solve():

        seed = [a for a in assump if a.value()]
        seed_names = [_nm(dmap[a]) for a in seed] if log_events is not None else None

        if s.solve(assumptions=seed) is True:
            # SAT, grow, to full MSS
            # Assumptions encode indicator constraints a -> c, find all true assumptions
            #    and those that could just as well be made true given the current solution
            mss = [a for a,c in zip(assump, soft) if a.value() or c.value()]
            for to_add in set(assump) - set(mss):
                if s.solve(assumptions=mss + [to_add]) is True:
                    mss.append(to_add)
            mcs = [a for a in assump if a not in frozenset(mss)] # take complement
            map_solver += cp.any(mcs) # block in map solver

            if log_events is not None:
                log_events.append({"type": "iter", "seed": seed_names, "kind": "MCS",
                                   "result": [_nm(dmap[a]) for a in mcs]})
            if return_mcs:
                yield "MCS", [dmap[a] for a in mcs]


        else: # UNSAT, shrink to MUS, re-use MUSX
            core = set(s.get_core())
            for c in sorted(core, key=deletion_order.get):
                if c not in core: # already removed
                    continue
                core.remove(c)
                if s.solve(assumptions=list(core)):
                    core.add(c)
                else: # UNSAT, shrink to new solver core (clause set refinement)
                    core = set(s.get_core())

            map_solver += ~cp.all(core) # block in map solver

            if log_events is not None:
                log_events.append({"type": "iter", "seed": seed_names, "kind": "MUS",
                                   "result": [_nm(dmap[a]) for a in core]})
            if return_mus:
                yield "MUS", [dmap[a] for a in core]


        # ensure solution hint is still active
        if do_solution_hint:
            map_solver.solution_hint(assump, hint)

    # map solver returned UNSAT: enumeration of this (soft, hard) is complete
    if enum_timing is not None:
        enum_timing.append(time.perf_counter() - _t_enum_start)


